### ISSUE TITLE
[$10 bounty] do not animate tipped emrals on page refresh

### ISSUE THREAD

**Issue by TaylorFrazier** [Emrals/Flutter#126]

**Comment by TaylorFrazier** [comment]
@britannio did you say you fixed this?  It is still happening on the latest build.

**Comment by britannio** [comment]
`I also fixed https://github.com/Emrals/Flutter/issues/126 but it doesn't apply anymore since adding a spinner to the bottom of those pages changed the refresh implementation.` That's what I said hence why I didn't reference this issue in the pr. This was the commit https://github.com/Emrals/Flutter/pull/139/commits/d70c5af2205a2b2da56d71236bd0c0b59f712924

**Comment by TaylorFrazier** [comment]
Ok that is the same issue.  This is still open then.
